Repository PrestaShop/blockwishlist, pull requests merged in 2022-01, with the labels that each got.

#141 Fixed RTL issues
  _dev/front/scss/_product.scss
  _dev/front/scss/_rtl.scss
  _dev/front/scss/common.scss
Labels: bug, QA ✔️

#144 Improved Workflow Build Release
  .github/workflows/build-release.yml
Labels: enhancement

#145 Add help sidebar to the statistic page
  src/Controller/WishlistConfigurationAdminController.php
Labels: QA ✔️

#147 Add bundles on every context
  views/templates/hook/displayHeader.tpl
Labels: QA ✔️

#155 Fix wrong condition on productAttributeId of addtowishlist modal
  _dev/front/js/components/AddToWishlist/AddToWishlist.vue
  public/addtowishlist.bundle.js
  public/button.bundle.js
  public/product.bundle.js
Labels: QA ✔️

#150 Add flash notification on form save
  src/Controller/WishlistConfigurationAdminController.php
Labels: QA ✔️

#152 Disable add-to-cart button when you click on it until the bootstrap modal hide
  _dev/front/js/components/Product/Product.vue
  package-lock.json
  public/backoffice.bundle.js
  public/form.bundle.js
  public/product.bundle.js
  public/productslist.bundle.js
  public/wishlist.css
  public/wishlistcontainer.bundle.js
Labels: QA ✔️

#151 Correct error when coming back to another combination
  _dev/front/js/components/Button/Button.vue
  public/button.bundle.js
  public/product.bundle.js
Labels: QA ✔️

#148 Remove unused class doing conflic with corejs
  _dev/front/js/components/Pagination/Pagination.vue
  _dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
  public/productslist.bundle.js
  views/templates/components/pagination.tpl
Labels: QA ✔️

#154 Use translated string for the Sort by: in lists
  _dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
  public/productslist.bundle.js
  views/templates/pages/products-list.tpl
Labels: QA ✔️

#156 Refacto card-block to card-body
  views/templates/admin/home.html.twig
  views/templates/admin/statistics.html.twig
Labels: QA ✔️

#158 Fix alert message width for theme-refacto
  _dev/front/js/components/Toast/Toast.vue
Labels: QA ✔️

#157 Make compatible with user account menu
  views/templates/pages/lists.tpl
Labels: QA ✔️
