Repository PrestaShop/blockwishlist, pull requests merged in 2023-02, with the labels that each got.

#207 Fix deprecations
  .github/workflows/php.yml
  blockwishlist.php
  composer.json
  config.xml
  controllers/front/view.php
  src/Calculator/StatisticsCalculator.php
  src/Database/Install.php
  src/Search/WishListProductSearchProvider.php
  tests/phpstan/phpstan-1.7.6.neon
  tests/phpstan/phpstan-1.7.7.neon
  tests/phpstan/phpstan-8.0.neon
Labels: enhancement, QA ✔️

#205 Fix overflow filter select on small screens
  _dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
Labels: QA ✔️

#210 Bump version to 3.0.0
  blockwishlist.php
  config.xml
Labels: enhancement

#209 Release 3.0.0
  .github/workflows/php.yml
  _dev/front/js/components/AddToWishlist/AddToWishlist.vue
  _dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
  _dev/front/scss/_modal.scss
  blockwishlist.php
  composer.json
  config.xml
  controllers/front/view.php
  package-lock.json
  package.json
  src/Calculator/StatisticsCalculator.php
  src/Database/Install.php
  src/Search/WishListProductSearchProvider.php
  tests/phpstan.sh
  tests/phpstan/phpstan-1.7.6.neon
  tests/phpstan/phpstan-1.7.7.neon
  tests/phpstan/phpstan-8.0.neon
Labels: enhancement, QA ✔️

#211 Import TranslatableInput from window.prestashop object
  _dev/back/js/form.js
  public/addtowishlist.bundle.js
  public/backoffice.bundle.js
  public/button.bundle.js
  public/form.bundle.js
  public/graphql.js
  public/product.bundle.js
  public/productslist.bundle.js
  public/vendors.js
  public/wishlist.css
  public/wishlistcontainer.bundle.js
  tsconfig.json
Labels: bug
