Repository PrestaShop/blockwishlist, pull requests merged in 2024-08, with the labels that each got.

#269 Functional Tests : Added scenario "Uninstall and delete module"
  .github/workflows/ui-test.yml
  tests/UI/campaigns/01_installation/05_uninstallAndDeleteModule.spec.ts
  tests/UI/docker-compose.yml
  tests/UI/package-lock.json
Labels: enhancement, QA ✔️

#273 UI Tests : Bump `@prestashop-core/ui-testing`
  tests/UI/package-lock.json
Labels: bug, QA ✔️

#274 Fixed ability to mark a product (with specific combination) as favorite
  _dev/front/js/components/Button/Button.vue
  tests/UI/campaigns/03_frontOffice/02_products/01_addProductToList.spec.ts
Labels: QA ✔️
