Repository PrestaShop/blockwishlist, pull requests merged in 2024-10, with the labels that each got.

#280 Fixed undefined array key category_name in statistics
  src/Calculator/StatisticsCalculator.php
Labels: QA ✔️

#290 Functional Tests : Enable Tests after #280
  tests/UI/campaigns/02_configuration/02_statisticsTabSettings.spec.ts
  tests/UI/package-lock.json
Labels: bug, QA ✔️

#276 v3.0.2
  .github/dependabot.yml
  .github/workflows/build-release.yml
  .github/workflows/js.yml
  .github/workflows/ui-test.yml
  .gitignore
  Makefile
  _dev/front/js/components/Button/Button.vue
  _dev/front/js/components/Create/Create.vue
  _dev/front/js/components/Delete/Delete.vue
  _dev/front/js/components/Login/Login.vue
  _dev/front/js/components/Product/Product.vue
  _dev/front/js/components/Rename/Rename.vue
  _dev/front/js/components/Share/Share.vue
  blockwishlist.php
  config.xml
  package-lock.json
  package.json
  src/Calculator/StatisticsCalculator.php
  src/Search/WishListProductSearchProvider.php
  tests/UI/campaigns/01_installation/05_uninstallAndDeleteModule.spec.ts
  tests/UI/campaigns/02_configuration/02_statisticsTabSettings.spec.ts
  tests/UI/campaigns/02_configuration/04_helpHeaderButtons.spec.ts
  tests/UI/campaigns/03_frontOffice/01_lists/03_shareList.spec.ts
  tests/UI/campaigns/03_frontOffice/02_products/01_addProductToList.spec.ts
  tests/UI/docker-compose.yml
  tests/UI/package-lock.json
  tests/UI/package.json
  tests/UI/playwright.config.ts
  tests/UI/tsconfig.json
  tests/UI/types/global.d.ts
  tests/js/Button.spec.js
  tests/js/Create.spec.js
  tests/js/Delete.spec.js
  tests/js/List.spec.js
  tests/js/Login.spec.js
  tests/js/Rename.spec.js
  tests/js/Toast.spec.js
  tests/js/setup.js
  upgrade/upgrade-0.3.0.php
  upgrade/upgrade-1.1.0.php
Labels: QA ✔️

#292 Upgrade upload-artifact
  .github/workflows/build-release.yml
Labels: QA ✔️

#294 Fixed CI publication
  .github/workflows/build-release.yml
Labels: Waiting for QA

#295 Functional Tests : Wishlist module - Reset module
  tests/UI/campaigns/01_installation/04_resetModule.spec.ts
  tests/UI/package-lock.json
Labels: enhancement, QA ✔️
